package fr.deuspheara.callapp.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF22005D)
val md_theme_light_secondary = Color(0xFF6A4FA3)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEADDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF25005A)
val md_theme_light_tertiary = Color(0xFF843BB3)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF4D9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2F004B)
val md_theme_light_error = Color(0xFFB81B32)
val md_theme_light_errorContainer = Color(0xFFFFDAD9)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410009)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFDF8FD)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)

val md_theme_dark_primary = Color(0xFFCFBCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378A)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFD2BBFF)
val md_theme_dark_onSecondary = Color(0xFF3B1D71)
val md_theme_dark_secondaryContainer = Color(0xFF523689)
val md_theme_dark_onSecondaryContainer = Color(0xFFEADDFF)
val md_theme_dark_tertiary = Color(0xFFE4B5FF)
val md_theme_dark_onTertiary = Color(0xFF4E0078)
val md_theme_dark_tertiaryContainer = Color(0xFF6A1D99)
val md_theme_dark_onTertiaryContainer = Color(0xFFF4D9FF)
val md_theme_dark_error = Color(0xFFFFB3B2)
val md_theme_dark_errorContainer = Color(0xFF920020)
val md_theme_dark_onError = Color(0xFF680014)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD9)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_outline = Color(0xFF91909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_surfaceTint = Color(0xFFCFBCFF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF141316)
val md_theme_dark_onSurface = Color(0xFFCAC5CA)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)


val seed = Color(0xFF6750A4)

